version: '3'

services:

  vonk-web:
    image: firely/server
    ports:
      - "8080:4080"
    environment:
      - VONK_Repository=SQLite
      - VONK_Administration:Repository=SQLite
      - VONK_License:LicenseFile=./license/firelyserver-license.json
    volumes:
      - .:/app/license
